build: false

environment:
  matrix:
    - nodejs_version: "0.10"

install:
  - npm update -g npm
  - npm install

test_script:
  - node --version
  - npm --version
  - node_modules/.bin/cake -n build test clean
